### ISSUE TITLE
<filename>_console.exe crashes on startup

### ISSUE THREAD

**Issue by Tortle6** [syegulalp/pypacker#1]
I sent the redistributable zip file for one of my projects to a few people (attached below). For one person, when opening client_console.exe, it flashes a black window (the console) for a split second before closing.

- Installing the latest version of Python did not seem to help the issue. 
- They were on Windows 10
- Others were able to run the same executable fine
- The zip was extracted before the executable was ran

None of us were able to recreate the issue.
Sorry for lack of information on this issue, there really isn't much I can add other than this
[client_exe.zip](https://github.com/syegulalp/pypacker/files/8249364/client_exe.zip)

**Comment by syegulalp** [comment]
Try running the .exe from an existing console window, instead of clicking on it. That should allow any errors to persist in the console.

**Comment by syegulalp** [comment]
Closing this for now but will reopen if there are updates.
